version: '2'
services:
    webapp:
        image: 'pkecastillo/basic-stack-webserver'
        restart: always
        container_name: webapp
        user: root
        network_mode: host
        cpu_shares: 2
        volumes:
            - ./DATA/webapp:/var/www/html:rw
        depends_on:
            - mariadb

    mariadb:
        image: 'mariadb:latest'
        container_name: mariadb
        user: root
        restart: unless-stopped
        # ports:
        #     - "3306:3306"
        network_mode: host
        cpu_shares: 2
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./DATA/mariadb:/var/lib/mysql
            
    adminer:
      image: adminer
      restart: always
      network_mode: host
      environment:
        ADMINER_PLUGINS: tables-filter tinymce
        ADMINER_DESIGN: hydra